import {
  Bug,
  Heart,
  HeartPulse,
  ImagePlus,
  MessageSquare,
  MousePointer2,
  Package,
  Plus,
  Sparkles,
  Terminal,
  TrendingUp,
  Truck,
  Users,
} from "lucide-react";
import { EcommerceCard } from "./cards/EcommerceCard";
import { HealthcareCard } from "./cards/HealthcareCard";
import { SocialCard } from "./cards/SocialCard";
import type { ImmersiveTheme } from "./types";

export const getImmersiveThemes = (): ImmersiveTheme[] => [
  {
    id: "software",
    title: "Software Development",
    tagline: "Edit the code below to customize your context menu in real-time",
    primaryColor: "#00ff41",
    secondaryColor: "#22c55e",
    glowColor: "rgba(0, 255, 65, 0.4)",
    mode: "dark",
    backgroundGradient: `
      radial-gradient(ellipse at 20% 20%, rgba(0, 255, 65, 0.08) 0%, transparent 50%),
      radial-gradient(ellipse at 80% 80%, rgba(0, 255, 65, 0.05) 0%, transparent 50%),
      linear-gradient(180deg, #000000 0%, #050505 100%)
    `,
    gridPattern: `
      repeating-linear-gradient(0deg, transparent, transparent 30px, rgba(0, 255, 65, 0.03) 30px, rgba(0, 255, 65, 0.03) 31px),
      repeating-linear-gradient(90deg, transparent, transparent 30px, rgba(0, 255, 65, 0.02) 30px, rgba(0, 255, 65, 0.02) 31px)
    `,
    floatingElements: [
      {
        icon: <span className="font-mono text-[#00ff41]/30">{"{"}</span>,
        position: { x: "10%", y: "15%" },
        parallaxMultiplier: 0.3,
        size: 64,
        opacity: 0.3,
        rotation: -15,
      },
      {
        icon: <span className="font-mono text-[#00ff41]/25">{"}"}</span>,
        position: { x: "90%", y: "80%" },
        parallaxMultiplier: 0.5,
        size: 72,
        opacity: 0.25,
        rotation: 10,
      },
      {
        icon: <span className="font-mono text-[#00ff41]/20">{"</>"}</span>,
        position: { x: "85%", y: "20%" },
        parallaxMultiplier: 0.4,
        size: 40,
        opacity: 0.2,
      },
      {
        icon: <Terminal className="text-[#00ff41]/20" />,
        position: { x: "5%", y: "75%" },
        parallaxMultiplier: 0.6,
        size: 32,
        opacity: 0.2,
        rotation: -5,
      },
      {
        icon: <Bug className="text-[#00ff41]/15" />,
        position: { x: "92%", y: "45%" },
        parallaxMultiplier: 0.35,
        size: 28,
        opacity: 0.15,
      },
    ],
    cardContent: null,
    menuItems: [
      { label: "Report bug", type: "bug", showComment: true },
      { label: "Send to Cursor", type: "cursor", showComment: false },
      { label: "Copy selector", type: "selector", showComment: false },
    ],
    menuStyle: {
      "--anyclick-menu-bg": "#0a0a0a",
      "--anyclick-menu-border": "#00ff41",
      "--anyclick-menu-text": "#00ff41",
      "--anyclick-menu-hover": "#001a00",
      "--anyclick-menu-accent": "#00ff41",
      backgroundColor: "#0a0a0a",
      border: "1px solid #00ff41",
      borderRadius: 8,
      boxShadow:
        "0 0 30px rgba(0, 255, 65, 0.3), 0 0 60px rgba(0, 255, 65, 0.1)",
      fontFamily: "ui-monospace, monospace",
      fontSize: 13,
    } as React.CSSProperties,
    pointerIcon: <Terminal size={18} className="text-[#00ff41]" />,
  },
  {
    id: "ecommerce",
    title: "E-commerce & Logistics",
    tagline: "Track, fulfill, and support with precision",
    primaryColor: "#f59e0b",
    secondaryColor: "#06b6d4",
    glowColor: "rgba(245, 158, 11, 0.4)",
    mode: "dark",
    backgroundGradient: `
      radial-gradient(ellipse at 30% 40%, rgba(245, 158, 11, 0.12) 0%, transparent 50%),
      radial-gradient(ellipse at 70% 60%, rgba(251, 191, 36, 0.08) 0%, transparent 50%),
      linear-gradient(180deg, rgba(15, 12, 8, 1) 0%, rgba(20, 15, 10, 1) 100%)
    `,
    gridPattern: `
      repeating-linear-gradient(45deg, transparent, transparent 60px, rgba(245, 158, 11, 0.02) 60px, rgba(245, 158, 11, 0.02) 61px)
    `,
    floatingElements: [
      {
        icon: <Package className="text-amber-400/50" />,
        position: { x: "20%", y: "25%" },
        parallaxMultiplier: 0.4,
        size: 36,
        opacity: 0.5,
        rotation: -10,
      },
      {
        icon: <Truck className="text-amber-300/40" />,
        position: { x: "80%", y: "70%" },
        parallaxMultiplier: 0.5,
        size: 32,
        opacity: 0.4,
        rotation: 5,
      },
      {
        icon: <Package className="text-yellow-400/30" />,
        position: { x: "85%", y: "20%" },
        parallaxMultiplier: 0.3,
        size: 24,
        opacity: 0.35,
      },
      {
        icon: <MessageSquare className="text-cyan-400/40" />,
        position: { x: "12%", y: "75%" },
        parallaxMultiplier: 0.45,
        size: 28,
        opacity: 0.4,
      },
    ],
    cardContent: <EcommerceCard />,
    menuItems: [
      { label: "Item missing", type: "missing", showComment: true },
      { label: "Shipping issue", type: "shipping", showComment: true },
      { label: "Escalate", type: "escalate", showComment: false },
    ],
    menuStyle: {
      "--anyclick-menu-bg": "#1c1917",
      "--anyclick-menu-border": "#f59e0b",
      "--anyclick-menu-text": "#fef3c7",
      "--anyclick-menu-hover": "#292524",
      "--anyclick-menu-accent": "#f59e0b",
      backgroundColor: "#1c1917",
      border: "1px solid #f59e0b",
      borderRadius: 10,
      boxShadow: "0 0 30px rgba(245, 158, 11, 0.25)",
    } as React.CSSProperties,
    pointerIcon: <Package size={18} className="text-amber-400" />,
  },
  {
    id: "healthcare",
    title: "Healthcare",
    tagline: "Patient care with clarity and compliance",
    primaryColor: "#10b981",
    secondaryColor: "#14b8a6",
    glowColor: "rgba(16, 185, 129, 0.3)",
    mode: "dark",
    backgroundGradient: `
      radial-gradient(ellipse at 30% 20%, rgba(16, 185, 129, 0.08) 0%, transparent 50%),
      radial-gradient(ellipse at 70% 80%, rgba(20, 184, 166, 0.06) 0%, transparent 50%),
      linear-gradient(180deg, #ffffff 0%, #f8fffe 50%, #f0fdf9 100%)
    `,
    floatingElements: [
      {
        icon: <Plus className="text-emerald-500/30" />,
        position: { x: "18%", y: "30%" },
        parallaxMultiplier: 0.35,
        size: 48,
        opacity: 0.3,
      },
      {
        icon: <Heart className="text-rose-400/25" />,
        position: { x: "82%", y: "65%" },
        parallaxMultiplier: 0.5,
        size: 36,
        opacity: 0.25,
      },
      {
        icon: <HeartPulse className="text-emerald-400/25" />,
        position: { x: "75%", y: "25%" },
        parallaxMultiplier: 0.4,
        size: 32,
        opacity: 0.25,
      },
      {
        icon: <Plus className="text-teal-500/20" />,
        position: { x: "10%", y: "70%" },
        parallaxMultiplier: 0.45,
        size: 28,
        opacity: 0.2,
      },
    ],
    cardContent: <HealthcareCard />,
    menuItems: [
      { label: "Check-in issue", type: "checkin", showComment: true },
      { label: "Vital alert", type: "vital", showComment: true },
      { label: "Flag urgent", type: "urgent", showComment: false },
    ],
    menuStyle: {
      "--anyclick-menu-bg": "#ffffff",
      "--anyclick-menu-border": "#10b981",
      "--anyclick-menu-text": "#065f46",
      "--anyclick-menu-hover": "#ecfdf5",
      "--anyclick-menu-accent": "#10b981",
      background: "#ffffff",
      border: "1px solid #10b981",
      borderRadius: 12,
      boxShadow:
        "0 4px 20px rgba(16, 185, 129, 0.15), 0 2px 8px rgba(0, 0, 0, 0.05)",
      color: "#065f46",
    } as React.CSSProperties,
    pointerIcon: <HeartPulse size={18} className="text-emerald-500" />,
  },
  {
    id: "social",
    title: "Social Media",
    tagline: "Create, engage, and analyze with flair",
    primaryColor: "#ec4899",
    secondaryColor: "#a855f7",
    glowColor: "rgba(236, 72, 153, 0.4)",
    mode: "dark",
    backgroundGradient: `
      radial-gradient(ellipse at 30% 30%, rgba(236, 72, 153, 0.15) 0%, transparent 50%),
      radial-gradient(ellipse at 70% 70%, rgba(168, 85, 247, 0.12) 0%, transparent 50%),
      linear-gradient(180deg, rgba(15, 8, 15, 1) 0%, rgba(20, 10, 20, 1) 100%)
    `,
    floatingElements: [
      {
        icon: <Sparkles className="text-pink-400/50" />,
        position: { x: "15%", y: "25%" },
        parallaxMultiplier: 0.4,
        size: 32,
        opacity: 0.5,
      },
      {
        icon: <Heart className="text-rose-400/45" />,
        position: { x: "85%", y: "30%" },
        parallaxMultiplier: 0.35,
        size: 28,
        opacity: 0.45,
      },
      {
        icon: <Users className="text-purple-400/40" />,
        position: { x: "80%", y: "70%" },
        parallaxMultiplier: 0.5,
        size: 30,
        opacity: 0.4,
      },
      {
        icon: <TrendingUp className="text-pink-300/35" />,
        position: { x: "12%", y: "75%" },
        parallaxMultiplier: 0.45,
        size: 26,
        opacity: 0.35,
      },
      {
        icon: <ImagePlus className="text-fuchsia-400/30" />,
        position: { x: "70%", y: "20%" },
        parallaxMultiplier: 0.3,
        size: 24,
        opacity: 0.3,
      },
    ],
    cardContent: <SocialCard />,
    menuItems: [
      { label: "Save asset", type: "save", showComment: false },
      { label: "Flag content", type: "flag", showComment: true },
      { label: "Quick reply", type: "reply", showComment: true },
    ],
    menuStyle: {
      "--anyclick-menu-bg": "rgba(236, 72, 153, 0.1)",
      "--anyclick-menu-border": "rgba(236, 72, 153, 0.3)",
      "--anyclick-menu-text": "#fdf2f8",
      "--anyclick-menu-hover": "rgba(236, 72, 153, 0.2)",
      "--anyclick-menu-accent": "#ec4899",
      background:
        "linear-gradient(135deg, rgba(236, 72, 153, 0.12), rgba(168, 85, 247, 0.08))",
      backdropFilter: "blur(16px)",
      border: "1px solid rgba(236, 72, 153, 0.25)",
      borderRadius: 14,
      boxShadow: "0 0 30px rgba(236, 72, 153, 0.2)",
    } as React.CSSProperties,
    pointerIcon: <Sparkles size={18} className="text-pink-400" />,
  },
];
