import type { CSSProperties } from "react";

export const menuStyles: Record<string, CSSProperties> = {
  overlay: {
    position: "fixed",
    inset: 0,
    zIndex: 9998,
  },
  container: {
    position: "fixed",
    zIndex: 9999,
    minWidth: "200px",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(0, 0, 0, 0.05)",
    overflow: "hidden",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: "14px",
  },
  header: {
    padding: "12px 16px",
    borderBottom: "1px solid #e5e5e5",
    color: "#666",
    fontSize: "12px",
    fontWeight: 500,
    textTransform: "uppercase" as const,
    letterSpacing: "0.5px",
  },
  itemList: {
    padding: "4px 0",
  },
  item: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px 16px",
    cursor: "pointer",
    transition: "background-color 0.15s",
    color: "#333",
    border: "none",
    backgroundColor: "transparent",
    width: "100%",
    textAlign: "left" as const,
    fontSize: "14px",
  },
  itemHover: {
    backgroundColor: "#f5f5f5",
  },
  itemIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    fontSize: "16px",
  },
  commentSection: {
    padding: "12px 16px",
    borderTop: "1px solid #e5e5e5",
  },
  commentInput: {
    width: "100%",
    minHeight: "60px",
    padding: "8px 12px",
    border: "1px solid #ddd",
    borderRadius: "6px",
    fontSize: "14px",
    fontFamily: "inherit",
    resize: "vertical" as const,
    outline: "none",
    boxSizing: "border-box" as const,
  },
  buttonRow: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    marginTop: "8px",
  },
  button: {
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background-color 0.15s, opacity 0.15s",
    border: "none",
  },
  cancelButton: {
    backgroundColor: "#f0f0f0",
    color: "#666",
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  submitButton: {
    backgroundColor: "#0066cc",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  submitButtonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
};

// Dark mode styles
export const darkMenuStyles: Record<string, CSSProperties> = {
  container: {
    ...menuStyles.container,
    backgroundColor: "#1a1a1a",
    boxShadow:
      "0 4px 12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255, 255, 255, 0.1)",
  },
  header: {
    ...menuStyles.header,
    borderBottom: "1px solid #333",
    color: "#888",
  },
  item: {
    ...menuStyles.item,
    color: "#e0e0e0",
  },
  itemHover: {
    backgroundColor: "#2a2a2a",
  },
  commentSection: {
    ...menuStyles.commentSection,
    borderTop: "1px solid #333",
  },
  commentInput: {
    ...menuStyles.commentInput,
    backgroundColor: "#2a2a2a",
    border: "1px solid #444",
    color: "#e0e0e0",
  },
  cancelButton: {
    ...menuStyles.cancelButton,
    backgroundColor: "#333",
    color: "#ccc",
  },
};

export const screenshotPreviewStyles: Record<string, React.CSSProperties> = {
  container: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  containerExpanded: {
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "90vw",
    maxWidth: "800px",
    maxHeight: "90vh",
    backgroundColor: "#fff",
    borderRadius: "12px",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    padding: "16px",
    zIndex: 10000,
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    padding: "24px",
  },
  loadingText: {
    fontSize: "13px",
    color: "#6b7280",
  },
  emptyContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "24px",
  },
  emptyText: {
    fontSize: "13px",
    color: "#6b7280",
    fontWeight: "500",
  },
  emptySubtext: {
    fontSize: "11px",
    color: "#9ca3af",
    textAlign: "center" as const,
  },
  emptyActions: {
    display: "flex",
    gap: "8px",
    marginTop: "8px",
  },
  retakeButtonOutline: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    fontSize: "12px",
    color: "#6b7280",
    backgroundColor: "transparent",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
    cursor: "pointer",
  },
  continueButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    fontSize: "12px",
    color: "#fff",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "500",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 4px",
  },
  headerTitle: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#374151",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sizeLabel: {
    fontSize: "11px",
    color: "#9ca3af",
  },
  iconButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    border: "none",
    backgroundColor: "transparent",
    borderRadius: "4px",
    cursor: "pointer",
    color: "#6b7280",
  },
  tabContainer: {
    display: "flex",
    gap: "4px",
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: "8px",
  },
  tab: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "2px 5px",
    fontSize: "12px",
    color: "#6b7280",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  tabActive: {
    backgroundColor: "#eff6ff",
    color: "#3b82f6",
    fontWeight: "500",
  },
  tabError: {
    color: "#ef4444",
  },
  tabSize: {
    fontSize: "10px",
    color: "#9ca3af",
  },
  previewContainer: {
    position: "relative",
    width: "100%",
    height: "150px",
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  previewContainerExpanded: {
    height: "60vh",
    maxHeight: "500px",
  },
  previewImage: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain",
  },
  noPreview: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: "#9ca3af",
  },
  errorPreview: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "16px",
    textAlign: "center" as const,
  },
  errorTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#ef4444",
  },
  errorMessage: {
    fontSize: "12px",
    color: "#6b7280",
    maxWidth: "250px",
    lineHeight: "1.4",
  },
  dimensionsInfo: {
    fontSize: "11px",
    color: "#9ca3af",
    textAlign: "center" as const,
  },
  actions: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "8px",
    borderTop: "1px solid #e5e7eb",
  },
  actionsRight: {
    display: "flex",
    gap: "8px",
  },
  retakeButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 16px",
    fontSize: "13px",
    color: "#fff",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "500",
  },
  retakeButtonSmall: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "4px 8px",
    fontSize: "11px",
    color: "#6b7280",
    backgroundColor: "transparent",
    border: "1px solid #e5e7eb",
    borderRadius: "4px",
    cursor: "pointer",
  },
};
